import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { parseAknDocument } from './xml-parser';
import type { AknDocument, Boletin, ProcedureEvent, TimelineEntry, SourceRef } from '$lib/types';

const RECETAS_DIR = 'research/2026-02-01/akndiff-poc';
const LEY_21735_DIR = 'research/2026-02-18/ley-21735/akn';
const LEY_18045_DIR = 'research/2026-02-18/ley-18045/akn';
const LEY_21670_DIR = 'research/2026-02-19/ley-21670/akn';
const LEY_17370_DIR = 'research/2026-02-19/ley-17370/akn';
const LEY_21120_DIR = 'research/2026-02-19/ley-21120/akn';
const EU_DMA_DIR = 'pipeline/data/eu/digital-markets-act/akn';
const EU_DSA_DIR = 'pipeline/data/eu/digital-services-act/akn';
const EU_AI_ACT_DIR = 'pipeline/data/eu/artificial-intelligence-act/akn';
const EU_CRA_DIR = 'pipeline/data/eu/horizontal-cybersecurity-requirements-for-products-with-digi/akn';
const EU_DATA_ACT_DIR = 'pipeline/data/eu/data-act/akn';
const US_S5_DIR = 'pipeline/data/us/s5-119/akn';
const US_S269_DIR = 'pipeline/data/us/s269-119/akn';
const US_S331_DIR = 'pipeline/data/us/s331-119/akn';
const US_S1582_DIR = 'pipeline/data/us/s1582-119/akn';
const ES_LO3_2018_DIR = 'pipeline/data/es/BOE-A-2018-16673/akn';
const ES_LEY39_2015_DIR = 'pipeline/data/es/BOE-A-2015-10565/akn';
const ES_LSSI_DIR = 'pipeline/data/es/BOE-A-2002-13758/akn';
const ES_TELECOM_DIR = 'pipeline/data/es/BOE-A-2022-10757/akn';
// ES Tramitación — Proyectos de Ley en tramitación parlamentaria
const ES_TRAM_ECONOMIA_SOCIAL_DIR = 'pipeline/data/es/121-000036/akn';
const ES_TRAM_DESPERDICIO_DIR = 'pipeline/data/es/121-000004/akn';
const ES_TRAM_MENORES_DIR = 'pipeline/data/es/121-000052/akn';
const ES_TRAM_JORNADA_DIR = 'pipeline/data/es/121-000058/akn';
const BOLETIN_DIRS: Record<string, string> = {
	// Ejemplos ficticios (recetas)
	'empanadas-de-pino': `${RECETAS_DIR}/receta-empanadas`,
	'feijoada-carioca': `${RECETAS_DIR}/receta-feijoada`,
	'milanesa-argentina': `${RECETAS_DIR}/receta-milanesa`,
	'pan-de-campo': `${RECETAS_DIR}/receta-pan`,
	'paella-valenciana': `${RECETAS_DIR}/receta-paella`,
	'ratatouille-nicoise': `${RECETAS_DIR}/receta-ratatouille`,
	// Ley 21.735 - Reforma de Pensiones (legislación real chilena)
	'ley-21735-boletin': `${LEY_21735_DIR}/boletin`,
	'ley-21735-dl-3500': `${LEY_21735_DIR}/dl-3500`,
	'ley-21735-dfl-5-2003': `${LEY_21735_DIR}/dfl-5-2003`,
	'ley-21735-ley-18045': `${LEY_21735_DIR}/ley-18045`,
	'ley-21735-dfl-28': `${LEY_21735_DIR}/dfl-28`,
	'ley-21735-ley-20880': `${LEY_21735_DIR}/ley-20880`,
	// Ley 18.045 — Historia de versiones (1981-2025)
	'ley-18045-historia': LEY_18045_DIR,
	// Ley 21.670 — Porte de armas aspirantes policiales (Boletín 15.995-02)
	'ley-21670-boletin': LEY_21670_DIR,
	// Boletín 17.370-17 — Cumplimiento alternativo de penas (RECHAZADO en Sala)
	'ley-17370-boletin': LEY_17370_DIR,
	// Ley 21.120 — Identidad de Género (Boletín 8924-07, con Comisión Mixta)
	'ley-21120-boletin': LEY_21120_DIR,
	// Pipeline CL outputs — generated by `npx tsx pipeline/cl/process.ts <boletin>`
	// Uncomment to view pipeline-generated boletines:
	// 'pipeline-17370': 'pipeline/data/cl/17370/akn',
	// 'pipeline-15995': 'pipeline/data/cl/15995/akn',
	// 'pipeline-8924': 'pipeline/data/cl/8924/akn',
	// EU — Digital Markets Act (Regulation 2022/1925, procedure 2020/0374(COD))
	'eu-dma': EU_DMA_DIR,
	// EU — Digital Services Act (Regulation 2022/2065, procedure 2020/0361(COD))
	'eu-dsa': EU_DSA_DIR,
	// EU — AI Act (Regulation 2024/1689, procedure 2021/0106(COD))
	'eu-ai-act': EU_AI_ACT_DIR,
	// EU — Cyber Resilience Act (Regulation 2024/2847, procedure 2022/0272(COD))
	'eu-cra': EU_CRA_DIR,
	// EU — Data Act (Regulation 2023/2854, procedure 2022/0047(COD))
	'eu-data-act': EU_DATA_ACT_DIR,
	// US — S.5 Laken Riley Act (Public Law 119-1, 119th Congress)
	'us-s5-laken-riley': US_S5_DIR,
	// US — S.269 Ending Improper Payments (Public Law 119-77, 119th Congress)
	'us-s269-improper-payments': US_S269_DIR,
	// US — S.331 HALT Fentanyl Act (Public Law 119-26, 119th Congress)
	'us-s331-halt-fentanyl': US_S331_DIR,
	// US — S.1582 GENIUS Act (Public Law 119-27, 119th Congress) — Stablecoin regulation
	'us-s1582-genius-act': US_S1582_DIR,
	// ES — LO 3/2018 Protección de Datos Personales (BOE-A-2018-16673)
	'es-lo3-2018-proteccion-datos': ES_LO3_2018_DIR,
	// ES — Ley 39/2015 Procedimiento Administrativo Común (BOE-A-2015-10565)
	'es-ley39-2015-procedimiento-administrativo': ES_LEY39_2015_DIR,
	// ES — Ley 34/2002 LSSI — Servicios de la Sociedad de la Información (BOE-A-2002-13758)
	'es-lssi-2002': ES_LSSI_DIR,
	// ES — Ley 11/2022 General de Telecomunicaciones (BOE-A-2022-10757)
	'es-telecom-2022': ES_TELECOM_DIR,
	// ES Tramitación — Proyectos de Ley en tramitación parlamentaria
	'es-tram-economia-social': ES_TRAM_ECONOMIA_SOCIAL_DIR,
	'es-tram-desperdicio-alimentario': ES_TRAM_DESPERDICIO_DIR,
	'es-tram-menores-digitales': ES_TRAM_MENORES_DIR,
	'es-tram-jornada-laboral': ES_TRAM_JORNADA_DIR
};

const SLUG_MAP: Record<string, string> = {
	'01-act-original.xml': 'original',
	'02-act-final.xml': 'final',
	'02-bill.xml': 'bill',
	'03-amendment-1.xml': 'amendment-1',
	'04-amendment-2.xml': 'amendment-2',
	'05-amendment-3.xml': 'amendment-3',
	'06-amendment-4.xml': 'amendment-4',
	'07-amendment-5.xml': 'amendment-5',
	'03-act-final.xml': 'final',
	'04-act-final.xml': 'final',
	'05-act-final.xml': 'final',
	'06-act-final.xml': 'final',
	'07-act-final.xml': 'final',
	'08-act-final.xml': 'final',
	'15-act-final.xml': 'final'
};

function fileToSlug(fileName: string): string {
	return SLUG_MAP[fileName] || fileName.replace('.xml', '').replace(/^\d+-/, '');
}

function slugToLabel(slug: string, boletinSlug?: string): string {
	// Boletín 15.480-13: bill-level timeline (original = Mensaje)
	if (boletinSlug === 'ley-21735-boletin') {
		const boletinLabels: Record<string, string> = {
			original: 'Mensaje Presidencial',
			bill: '1er Trámite: C. Diputados',
			'amendment-1': '2do Trámite: Senado',
			'amendment-2': '3er Trámite: C. Diputados',
			'amendment-3': 'Tribunal Constitucional',
			final: 'Ley Promulgada'
		};
		return boletinLabels[slug] || slug;
	}
	// Boletín 15.995-02 (Ley 21.670): complete legislative process
	if (boletinSlug === 'ley-21670-boletin') {
		const ley21670Labels: Record<string, string> = {
			original: 'Ley 17.798 (pre-reforma)',
			bill: 'Moción Original',
			'amendment-1': '1er Trámite: C. Diputados',
			'amendment-2': '2do Trámite: Senado',
			final: 'Ley 21.670 Publicada'
		};
		return ley21670Labels[slug] || slug;
	}
	// Ley 21.120 — Identidad de Género (Boletín 8924-07, con Comisión Mixta)
	if (boletinSlug === 'ley-21120-boletin') {
		const ley21120Labels: Record<string, string> = {
			bill: 'Moción Original',
			'amendment-1': '1er Trámite: Senado',
			'amendment-2': '2do Trámite: Cámara (RECHAZADO)',
			'amendment-3': 'Comisión Mixta',
			final: 'Ley 21.120 Publicada'
		};
		return ley21120Labels[slug] || slug;
	}
	// EU regulations — shared labels
	if (boletinSlug?.startsWith('eu-')) {
		const euLabels: Record<string, string> = {
			original: 'COM Proposal',
			'amendment-1': 'EP First Reading',
			final: 'Regulation Published'
		};
		return euLabels[slug] || slug;
	}
	// Boletín 17.370-17: cumplimiento alternativo penas (rejected in Sala)
	if (boletinSlug === 'ley-17370-boletin') {
		const ley17370Labels: Record<string, string> = {
			bill: 'Moción Original',
			'amendment-1': 'Informe Comisión + Sala (RECHAZADO)'
		};
		return ley17370Labels[slug] || slug;
	}
	// US bills
	if (boletinSlug === 'us-s5-laken-riley') {
		const usLabels: Record<string, string> = {
			bill: 'Placed on Calendar (PCS)',
			'amendment-1': 'Senate Passage (64-35)',
			'amendment-2': 'House Passage (263-156)',
			final: 'Public Law 119-1'
		};
		return usLabels[slug] || slug;
	}
	if (boletinSlug === 'us-s269-improper-payments') {
		const usLabels: Record<string, string> = {
			bill: 'Introduced (IS)',
			'amendment-1': 'Senate Passage (Voice Vote)',
			'amendment-2': 'House Passage (Voice Vote)',
			final: 'Public Law 119-77'
		};
		return usLabels[slug] || slug;
	}
	if (boletinSlug === 'us-s331-halt-fentanyl') {
		const usLabels: Record<string, string> = {
			bill: 'Introduced (IS)',
			'amendment-1': 'Senate Passage (84-16)',
			'amendment-2': 'House Passage (321-104)',
			final: 'Public Law 119-26'
		};
		return usLabels[slug] || slug;
	}
	if (boletinSlug === 'us-s1582-genius-act') {
		const usLabels: Record<string, string> = {
			bill: 'Placed on Calendar (PCS)',
			'amendment-1': 'Senate Passage (68-30)',
			'amendment-2': 'House Passage (308-122)',
			final: 'Public Law 119-27'
		};
		return usLabels[slug] || slug;
	}
	// Ley 21.735 per-norm timelines (original = pre-reform law)
	if (boletinSlug?.startsWith('ley-21735-')) {
		const leyLabels: Record<string, string> = {
			original: 'Ley Original',
			bill: 'Mensaje Presidencial',
			'amendment-1': '1er Trámite: C. Diputados',
			'amendment-2': '2do Trámite: Senado',
			'amendment-3': '3er Trámite: C. Diputados',
			'amendment-4': 'Tribunal Constitucional',
			final: 'Ley Promulgada'
		};
		return leyLabels[slug] || slug;
	}
	// ES — Leyes consolidadas del BOE
	if (boletinSlug === 'es-ley39-2015-procedimiento-administrativo') {
		const esLabels: Record<string, string> = {
			original: 'Ley 39/2015 (publicacion original)',
			final: 'Texto Vigente'
		};
		return esLabels[slug] || slug;
	}
	if (boletinSlug === 'es-lo3-2018-proteccion-datos') {
		const esLabels: Record<string, string> = {
			original: 'LO 3/2018 (publicacion original)',
			'amendment-1': 'Sentencia TC 76/2019',
			'amendment-2': 'Mod. LO 3/2020 (art. 83)',
			'amendment-3': 'Mod. LO 7/2021 (arts. 2, 44, DA 15)',
			'amendment-4': 'Mod. Ley 2/2023 (art. 24)',
			'amendment-5': 'Mod. Ley 11/2023 (arts. 48-67, DA 23)',
			'amendment-6': 'Mod. Ley 10/2025 (art. 23)',
			final: 'Texto Vigente'
		};
		return esLabels[slug] || slug;
	}
	if (boletinSlug === 'es-lssi-2002') {
		const esLabels: Record<string, string> = {
			original: 'Ley 34/2002 LSSI (publicacion original)',
			final: 'Texto Vigente'
		};
		return esLabels[slug] || slug;
	}
	if (boletinSlug === 'es-telecom-2022') {
		const esLabels: Record<string, string> = {
			original: 'Ley 11/2022 Telecomunicaciones (publicacion original)',
			final: 'Texto Vigente'
		};
		return esLabels[slug] || slug;
	}
	// ES Tramitación — bills in parliamentary process (use docTitle from XML as label)
	if (boletinSlug?.startsWith('es-tram-')) {
		// For tramitación, we prefer the label from the AKN XML (set via docTitle)
		// Return slug as-is so buildTimeline() falls through to docTitle
		return slug;
	}
	const labels: Record<string, string> = {
		original: 'Ley Original',
		bill: 'Proyecto de Ley',
		'amendment-1': 'Indicación 1',
		'amendment-2': 'Indicación 2',
		'amendment-3': 'Indicación 3',
		'amendment-4': 'Indicación 4',
		'amendment-5': 'Indicación 5',
		final: 'Ley Promulgada'
	};
	return labels[slug] || slug;
}

const LEYCHILE_URL = 'https://www.bcn.cl/leychile/consulta/N';

function leyChileSource(idNorma: number): { url: string; label: string } {
	return { url: `${LEYCHILE_URL}?i=${idNorma}`, label: 'LeyChile' };
}

function slugToSource(slug: string, boletinSlug?: string): { url: string; label: string } | undefined {
	// Ley 21.735 — Boletín 15.480-13
	if (boletinSlug === 'ley-21735-boletin') {
		const map: Record<string, { url: string; label: string }> = {
			original: { url: senadoDocUrl(16006, 'mensaje_mocion'), label: 'Mensaje' },
			bill: { url: senadoDocUrl(32980, 'ofic'), label: 'Oficio 1er Trámite' },
			'amendment-1': { url: senadoDocUrl(34510, 'ofic'), label: 'Oficio 2do Trámite' },
			'amendment-2': { url: senadoDocUrl(34530, 'ofic'), label: 'Oficio 3er Trámite' },
			'amendment-3': { url: senadoDocUrl(34575, 'ofic'), label: 'Fallo TC' },
			final: leyChileSource(1212060)
		};
		return map[slug];
	}
	// Ley 21.735 — normas modificadas
	if (boletinSlug?.startsWith('ley-21735-')) {
		const normIds: Record<string, number> = {
			'ley-21735-dl-3500': 7147,
			'ley-21735-dfl-5-2003': 221322,
			'ley-21735-ley-18045': 29472,
			'ley-21735-dfl-28': 4115,
			'ley-21735-ley-20880': 1086062
		};
		if (slug === 'original' || slug === 'final') {
			const id = normIds[boletinSlug];
			if (id) return leyChileSource(id);
		}
		return { url: senadoDocUrl(16006, 'mensaje_mocion'), label: 'Senado' };
	}
	// Ley 18.045 — Historia de versiones (LeyChile)
	if (boletinSlug === 'ley-18045-historia') {
		return leyChileSource(29472);
	}
	// Ley 21.670 — Boletín 15.995-02
	if (boletinSlug === 'ley-21670-boletin') {
		const map: Record<string, { url: string; label: string }> = {
			original: { url: leyChileUrl(29120, '2023-06-04'), label: 'LeyChile' },
			bill: { url: senadoDocUrl(16536, 'mensaje_mocion'), label: 'Moción' },
			'amendment-1': { url: senadoDocUrl(33029, 'ofic'), label: 'Oficio 1er Trámite' },
			'amendment-2': { url: senadoDocUrl(33217, 'ofic'), label: 'Oficio 2do Trámite' },
			final: { url: leyChileUrl(29120, '2024-06-13'), label: 'LeyChile' }
		};
		return map[slug];
	}
	// Boletín 17.370-17
	if (boletinSlug === 'ley-17370-boletin') {
		const map: Record<string, { url: string; label: string }> = {
			bill: { url: senadoDocUrl(18004, 'mensaje_mocion'), label: 'Moción' },
			'amendment-1': { url: senadoDocUrl(27646, 'info'), label: 'Informe Comisión' }
		};
		return map[slug];
	}
	// EU regulations — EUR-Lex source links
	if (boletinSlug?.startsWith('eu-')) {
		const eurlex = 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:';
		const euCelex: Record<string, Record<string, string>> = {
			'eu-dma': { original: '52020PC0842', 'amendment-1': '52021AP0499', final: '32022R1925' },
			'eu-dsa': { original: '52020PC0825', 'amendment-1': '52022AP0014', final: '32022R2065' },
			'eu-ai-act': { original: '52021PC0206', 'amendment-1': '52023AP0236', final: '32024R1689' },
			'eu-cra': { original: '52022PC0454', final: '32024R2847' },
			'eu-data-act': { original: '52022PC0068', 'amendment-1': '52023AP0069', final: '32023R2854' }
		};
		const celex = euCelex[boletinSlug]?.[slug];
		if (celex) return { url: `${eurlex}${celex}`, label: 'EUR-Lex' };
		return undefined;
	}
	// US bills
	if (boletinSlug === 'us-s5-laken-riley') {
		const congressGov = 'https://www.congress.gov';
		const map: Record<string, { url: string; label: string }> = {
			bill: { url: `${congressGov}/bill/119th-congress/senate-bill/5/text/pcs`, label: 'Congress.gov' },
			'amendment-1': { url: `${congressGov}/bill/119th-congress/senate-bill/5/text/es`, label: 'Congress.gov' },
			'amendment-2': { url: `${congressGov}/bill/119th-congress/senate-bill/5/text/enr`, label: 'Congress.gov' },
			final: { url: `${congressGov}/bill/119th-congress/senate-bill/5/text/pl`, label: 'Congress.gov' }
		};
		return map[slug];
	}
	if (boletinSlug === 'us-s269-improper-payments') {
		const congressGov = 'https://www.congress.gov';
		const map: Record<string, { url: string; label: string }> = {
			bill: { url: `${congressGov}/bill/119th-congress/senate-bill/269/text/is`, label: 'Congress.gov' },
			'amendment-1': { url: `${congressGov}/bill/119th-congress/senate-bill/269/text/es`, label: 'Congress.gov' },
			'amendment-2': { url: `${congressGov}/bill/119th-congress/senate-bill/269/text/enr`, label: 'Congress.gov' },
			final: { url: `${congressGov}/bill/119th-congress/senate-bill/269/text/pl`, label: 'Congress.gov' }
		};
		return map[slug];
	}
	if (boletinSlug === 'us-s331-halt-fentanyl') {
		const congressGov = 'https://www.congress.gov';
		const map: Record<string, { url: string; label: string }> = {
			bill: { url: `${congressGov}/bill/119th-congress/senate-bill/331/text/is`, label: 'Congress.gov' },
			'amendment-1': { url: `${congressGov}/bill/119th-congress/senate-bill/331/text/es`, label: 'Congress.gov' },
			'amendment-2': { url: `${congressGov}/bill/119th-congress/senate-bill/331/text/enr`, label: 'Congress.gov' },
			final: { url: `${congressGov}/bill/119th-congress/senate-bill/331/text/pl`, label: 'Congress.gov' }
		};
		return map[slug];
	}
	if (boletinSlug === 'us-s1582-genius-act') {
		const congressGov = 'https://www.congress.gov';
		const map: Record<string, { url: string; label: string }> = {
			bill: { url: `${congressGov}/bill/119th-congress/senate-bill/1582/text/pcs`, label: 'Congress.gov' },
			'amendment-1': { url: `${congressGov}/bill/119th-congress/senate-bill/1582/text/es`, label: 'Congress.gov' },
			'amendment-2': { url: `${congressGov}/bill/119th-congress/senate-bill/1582/text/enr`, label: 'Congress.gov' },
			final: { url: `${congressGov}/bill/119th-congress/senate-bill/1582/text/pl`, label: 'Congress.gov' }
		};
		return map[slug];
	}
	// Ley 21.120 — Boletín 8924-07
	if (boletinSlug === 'ley-21120-boletin') {
		const map: Record<string, { url: string; label: string }> = {
			bill: { url: senadoDocUrl(9331, 'mensaje_mocion'), label: 'Moción' },
			'amendment-1': { url: senadoDocUrl(22438, 'ofic'), label: 'Oficio 1er Trámite' },
			'amendment-2': { url: senadoDocUrl(23141, 'ofic'), label: 'Oficio 2do Trámite' },
			'amendment-3': { url: senadoDocUrl(20587, 'info'), label: 'Informe C. Mixta' },
			final: leyChileSource(1126480)
		};
		return map[slug];
	}
	// ES Tramitación — bills in parliamentary process (source URLs from config.json)
	if (boletinSlug?.startsWith('es-tram-')) {
		// Source URLs are dynamically set from config.json in loadBoletin()
		return undefined;
	}
	// ES — BOE consolidated laws
	if (boletinSlug?.startsWith('es-')) {
		const boe = 'https://www.boe.es/buscar/act.php?id=';
		// Extract BOE ID from slug: es-lo3-2018-proteccion-datos → BOE-A-2018-16673
		// We hardcode known ones; for dynamic lookup we'd need the config
		const boeIds: Record<string, string> = {
			'es-lo3-2018-proteccion-datos': 'BOE-A-2018-16673',
			'es-ley39-2015-procedimiento-administrativo': 'BOE-A-2015-10565',
			'es-lssi-2002': 'BOE-A-2002-13758',
			'es-telecom-2022': 'BOE-A-2022-10757'
		};
		const boeId = boeIds[boletinSlug];
		if (boeId) {
			return { url: `${boe}${boeId}`, label: 'BOE' };
		}
	}
	return undefined;
}

function buildTimeline(documents: AknDocument[], boletinSlug?: string): TimelineEntry[] {
	return documents.map((doc) => {
		const slug = fileToSlug(doc.fileName);
		const mappedLabel = slugToLabel(slug, boletinSlug);
		// If slugToLabel returned the raw slug (no mapping), use docTitle from XML
		const label = mappedLabel === slug ? (doc.prefaceTitle || slug) : mappedLabel;
		const source = slugToSource(slug, boletinSlug);
		const entry: TimelineEntry = {
			slug,
			label,
			date: doc.frbr.date,
			type: doc.type,
			author: doc.frbr.authorLabel,
			fileName: doc.fileName,
			sourceUrl: source?.url,
			sourceLabel: source?.label
		};
		if (doc.changeSet?.vote) {
			entry.voteResult = doc.changeSet.vote.result;
		}
		return entry;
	});
}

export async function loadRawXml(boletinSlug: string, fileName: string): Promise<string> {
	const dirName = BOLETIN_DIRS[boletinSlug];
	if (!dirName) throw new Error(`Unknown boletin: ${boletinSlug}`);
	return readFile(join(process.cwd(), dirName, fileName), 'utf-8');
}

const LEY_21735_BASE = 'research/2026-02-18/ley-21735';
const LEY_21670_BASE = 'research/2026-02-19/ley-21670';
const LEY_17370_BASE = 'research/2026-02-19/ley-17370';
const LEY_21120_DOCS = 'research/2026-02-19/ley-21120-docs';
const LEY_18045_BASE = 'research/2026-02-18/ley-18045';

// Official source URL helpers — direct document downloads from Senate + LeyChile
const SENADO_DOC = 'https://tramitacion.senado.cl/appsenado/index.php?mo=tramitacion&ac=getDocto';
const LEYCHILE_NAV = 'https://nuevo.leychile.cl/servicios/Navegar';

/** Direct download URL for a Senate document by iddocto + tipodoc */
function senadoDocUrl(iddocto: number, tipodoc: string): string {
	return `${SENADO_DOC}&iddocto=${iddocto}&tipodoc=${tipodoc}`;
}
function leyChileUrl(idNorma: number, version?: string): string {
	if (version) return `${LEYCHILE_NAV}/?idNorma=${idNorma}&idVersion=${version}`;
	return `${LEYCHILE_NAV}/?idNorma=${idNorma}`;
}

function src(label: string, path: string, type: SourceRef['type'] = 'text', url?: string): SourceRef {
	return { label, path, type, url };
}

// idNorma values for LeyChile
const NORM_IDS: Record<string, number> = {
	'dl-3500': 7147,
	'dfl-5-2003': 221322,
	'ley-18045': 29472,
	'dfl-28': 4115,
	'ley-20880': 1086062
};

/** Maps each boletín + version slug to the source documents used to generate the AKN XML. */
export function getSourceDocuments(boletinSlug: string, versionSlug: string): SourceRef[] {
	// ── Ley 21.735 — Boletín (bill-level timeline) ──
	if (boletinSlug === 'ley-21735-boletin') {
		const docs: Record<string, SourceRef[]> = {
			original: [
				src('Mensaje Presidencial', `${LEY_21735_BASE}/oficios/mensaje.txt`, 'text',
					senadoDocUrl(16006, 'mensaje_mocion'))
			],
			bill: [
				src('Oficio 1er Trámite', `${LEY_21735_BASE}/oficios/1er-tramite-oficio.txt`, 'text',
					senadoDocUrl(32980, 'ofic')),
				src('Certificado Comisión Trabajo', `${LEY_21735_BASE}/oficios/1er-tramite-oficio.txt`, 'text',
					senadoDocUrl(26258, 'info'))
			],
			'amendment-1': [
				src('Oficio 2do Trámite', `${LEY_21735_BASE}/oficios/2do-tramite-oficio.txt`, 'text',
					senadoDocUrl(34510, 'ofic')),
				src('Votación Senado', `${LEY_21735_BASE}/votes/senado-votes.xml`, 'xml',
					senadoDocUrl(9872, 'votacion'))
			],
			'amendment-2': [
				src('Oficio 3er Trámite (aprobación)', `${LEY_21735_BASE}/votes/camara-votes.xml`, 'xml',
					senadoDocUrl(34530, 'ofic'))
			],
			final: [
				src('Ley 21.735 — LeyChile', `${LEY_21735_BASE}/json/ley-21735-post.json`, 'json',
					leyChileUrl(1212060))
			]
		};
		return docs[versionSlug] || [];
	}

	// ── Ley 21.735 — Normas modificadas (per-norm timelines) ──
	if (boletinSlug.startsWith('ley-21735-')) {
		const normSlug = boletinSlug.replace('ley-21735-', '');
		const idNorma = NORM_IDS[normSlug];
		const lcPre = idNorma ? leyChileUrl(idNorma, '2025-03-25') : undefined;
		const lcPost = idNorma ? leyChileUrl(idNorma, '2025-03-26') : undefined;
		const docs: Record<string, SourceRef[]> = {
			original: [
				src('LeyChile (pre-reforma)', `${LEY_21735_BASE}/json/${normSlug}-pre.json`, 'json', lcPre)
			],
			bill: [
				src('Diff pre→post', `${LEY_21735_BASE}/diff/${normSlug}-changes.json`, 'json',
					senadoDocUrl(16006, 'mensaje_mocion'))
			],
			'amendment-1': [
				src('Certificado Comisión Trabajo', `${LEY_21735_BASE}/votes/camara-votes.xml`, 'xml',
					senadoDocUrl(26258, 'info'))
			],
			'amendment-2': [
				src('Votación Senado', `${LEY_21735_BASE}/votes/senado-votes.xml`, 'xml',
					senadoDocUrl(9872, 'votacion'))
			],
			'amendment-3': [
				src('Oficio 3er Trámite (aprobación)', `${LEY_21735_BASE}/votes/camara-votes.xml`, 'xml',
					senadoDocUrl(34530, 'ofic'))
			],
			final: [
				src('LeyChile (post-reforma)', `${LEY_21735_BASE}/json/${normSlug}-post.json`, 'json', lcPost)
			]
		};
		return docs[versionSlug] || [];
	}

	// ── Ley 18.045 — Historia de versiones (LeyChile) ──
	if (boletinSlug === 'ley-18045-historia') {
		const lc = leyChileUrl(29472);
		if (versionSlug === 'original') {
			return [src('LeyChile v1 (1981)', `${LEY_18045_BASE}/json/v01-1981-10-22.json`, 'json',
				leyChileUrl(29472, '1981-10-22'))];
		}
		if (versionSlug === 'final') {
			return [src('LeyChile v32 (2025)', `${LEY_18045_BASE}/json/v32-2025-03-26.json`, 'json',
				leyChileUrl(29472, '2025-03-26'))];
		}
		const m = versionSlug.match(/^amendment-(\d+)$/);
		if (m) {
			const vNum = String(Number(m[1]) + 1).padStart(2, '0');
			return [src(`LeyChile v${vNum}`, `${LEY_18045_BASE}/json/versions-index.json`, 'json', lc)];
		}
		return [];
	}

	// ── Ley 21.670 — Control de Armas (Boletín 15.995-02) ──
	if (boletinSlug === 'ley-21670-boletin') {
		const docs: Record<string, SourceRef[]> = {
			original: [
				src('Ley 17.798 — LeyChile', `${LEY_21670_BASE}/json/ley-17798-pre-reform.json`, 'json',
					leyChileUrl(29120, '2023-06-04'))
			],
			bill: [
				src('Moción Original', `${LEY_21670_BASE}/docs/01-mocion.txt`, 'text',
					senadoDocUrl(16536, 'mensaje_mocion'))
			],
			'amendment-1': [
				src('Informe Comisión Defensa', `${LEY_21670_BASE}/docs/03-informe-comision-camara.txt`, 'text',
					senadoDocUrl(26310, 'info')),
				src('Oficio 1er Trámite', `${LEY_21670_BASE}/docs/04-oficio-1er-tramite.txt`, 'text',
					senadoDocUrl(33029, 'ofic'))
			],
			'amendment-2': [
				src('Oficio Modificaciones Senado', `${LEY_21670_BASE}/docs/07-oficio-modificaciones-senado.txt`, 'text',
					senadoDocUrl(33217, 'ofic')),
				src('Votación Senado', `${LEY_21670_BASE}/docs/07-oficio-modificaciones-senado.txt`, 'text',
					senadoDocUrl(9665, 'votacion'))
			],
			final: [
				src('Ley 17.798 reformada — LeyChile', `${LEY_21670_BASE}/json/ley-17798-post-reform.json`, 'json',
					leyChileUrl(29120, '2024-06-13'))
			]
		};
		return docs[versionSlug] || [];
	}

	// ── Boletín 17.370-17 — Cumplimiento alternativo penas (RECHAZADO) ──
	if (boletinSlug === 'ley-17370-boletin') {
		const docs: Record<string, SourceRef[]> = {
			bill: [
				src('Moción Original', `${LEY_17370_BASE}/docs/01-mocion.txt`, 'text',
					senadoDocUrl(18004, 'mensaje_mocion'))
			],
			'amendment-1': [
				src('Informe Comisión DDHH', `${LEY_17370_BASE}/docs/04-informe-comision-ddhh.txt`, 'text',
					senadoDocUrl(27646, 'info')),
				src('Votación Sala (Rechazado)', `${LEY_17370_BASE}/docs/04-informe-comision-ddhh.txt`, 'text',
					senadoDocUrl(10101, 'votacion'))
			]
		};
		return docs[versionSlug] || [];
	}

	// ── EU regulations ──
	if (boletinSlug?.startsWith('eu-')) {
		const eurlex = 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:';
		const euConfigs: Record<string, { slug: string; bill: string; ep: string | null; taRef: string | null; final: string; comLabel: string; regLabel: string }> = {
			'eu-dma': { slug: 'digital-markets-act', bill: '52020PC0842', ep: '52021AP0499', taRef: null, final: '32022R1925', comLabel: 'COM(2020) 842', regLabel: 'Regulation (EU) 2022/1925' },
			'eu-dsa': { slug: 'digital-services-act', bill: '52020PC0825', ep: '52022AP0014', taRef: null, final: '32022R2065', comLabel: 'COM(2020) 825', regLabel: 'Regulation (EU) 2022/2065' },
			'eu-ai-act': { slug: 'artificial-intelligence-act', bill: '52021PC0206', ep: '52023AP0236', taRef: null, final: '32024R1689', comLabel: 'COM(2021) 206', regLabel: 'Regulation (EU) 2024/1689' },
			'eu-cra': { slug: 'horizontal-cybersecurity-requirements-for-products-with-digi', bill: '52022PC0454', ep: null, taRef: null, final: '32024R2847', comLabel: 'COM(2022) 454', regLabel: 'Regulation (EU) 2024/2847' },
			'eu-data-act': { slug: 'data-act', bill: '52022PC0068', ep: '52023AP0069', taRef: 'TA-9-2023-0385', final: '32023R2854', comLabel: 'COM(2022) 68', regLabel: 'Regulation (EU) 2023/2854' }
		};
		const cfg = euConfigs[boletinSlug];
		if (cfg) {
			const srcDir = `pipeline/data/eu/${cfg.slug}/sources`;
			const docs: Record<string, SourceRef[]> = {
				original: [src(`${cfg.comLabel} Proposal`, `${srcDir}/${cfg.bill}-raw.xhtml`, 'text', `${eurlex}${cfg.bill}`)],
				final: [src(`${cfg.regLabel} Formex`, `${srcDir}/${cfg.final}-formex.xml`, 'xml', `${eurlex}${cfg.final}`)]
			};
			if (cfg.ep) {
				if (cfg.taRef) {
					// EP Position (full text, e.g. Data Act)
					docs['amendment-1'] = [src('EP Position (adopted text)', `${srcDir}/${cfg.taRef}_EN.html`, 'text', `${eurlex}${cfg.ep}`)];
				} else {
					// EP Amendments (OJ table format)
					docs['amendment-1'] = [src('EP Legislative Resolution', `${srcDir}/${cfg.ep}-ep-amendments.html`, 'text', `${eurlex}${cfg.ep}`)];
				}
			}
			return docs[versionSlug] || [];
		}
	}

	// ── US bills ──
	if (boletinSlug === 'us-s5-laken-riley') {
		const usBase = 'pipeline/data/us/s5-119/sources';
		const congressGov = 'https://www.congress.gov';
		const docs: Record<string, SourceRef[]> = {
			bill: [
				src('S.5 — Placed on Calendar', `${usBase}/01-pcs.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/5/text/pcs`)
			],
			'amendment-1': [
				src('S.5 — Engrossed in Senate', `${usBase}/02-es.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/5/text/es`),
				src('Senate Roll Call Vote #7', `${usBase}/vote-senate-007.xml`, 'xml',
					'https://www.senate.gov/legislative/LIS/roll_call_votes/vote1191/vote_119_1_00007.htm')
			],
			'amendment-2': [
				src('House Roll Call Vote #23', `${usBase}/vote-house-023.xml`, 'xml',
					'https://clerk.house.gov/Votes/202523')
			],
			final: [
				src('S.5 — Enrolled Bill', `${usBase}/03-enr.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/5/text/enr`)
			]
		};
		return docs[versionSlug] || [];
	}
	if (boletinSlug === 'us-s269-improper-payments') {
		const usBase = 'pipeline/data/us/s269-119/sources';
		const congressGov = 'https://www.congress.gov';
		const docs: Record<string, SourceRef[]> = {
			bill: [
				src('S.269 — Introduced in Senate', `${usBase}/01-is.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/269/text/is`)
			],
			'amendment-1': [
				src('S.269 — Engrossed in Senate', `${usBase}/02-es.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/269/text/es`)
			],
			'amendment-2': [
				src('S.269 — Enrolled Bill', `${usBase}/03-enr.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/269/text/enr`)
			],
			final: [
				src('S.269 — Enrolled Bill', `${usBase}/03-enr.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/269/text/pl`)
			]
		};
		return docs[versionSlug] || [];
	}
	if (boletinSlug === 'us-s331-halt-fentanyl') {
		const usBase = 'pipeline/data/us/s331-119/sources';
		const congressGov = 'https://www.congress.gov';
		const docs: Record<string, SourceRef[]> = {
			bill: [
				src('S.331 — Introduced in Senate', `${usBase}/01-is.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/331/text/is`)
			],
			'amendment-1': [
				src('S.331 — Engrossed in Senate', `${usBase}/02-es.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/331/text/es`),
				src('Senate Roll Call Vote #127', `${usBase}/vote-senate-127.xml`, 'xml',
					'https://www.senate.gov/legislative/LIS/roll_call_votes/vote1191/vote_119_1_00127.htm')
			],
			'amendment-2': [
				src('House Roll Call Vote #166', `${usBase}/vote-house-166.xml`, 'xml',
					'https://clerk.house.gov/Votes/2025166')
			],
			final: [
				src('S.331 — Enrolled Bill', `${usBase}/03-enr.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/331/text/enr`)
			]
		};
		return docs[versionSlug] || [];
	}
	if (boletinSlug === 'us-s1582-genius-act') {
		const usBase = 'pipeline/data/us/s1582-119/sources';
		const congressGov = 'https://www.congress.gov';
		const docs: Record<string, SourceRef[]> = {
			bill: [
				src('S.1582 — Placed on Calendar', `${usBase}/01-pcs.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/1582/text/pcs`)
			],
			'amendment-1': [
				src('S.1582 — Engrossed in Senate', `${usBase}/02-es.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/1582/text/es`),
				src('Senate Roll Call Vote #318', `${usBase}/vote-senate-318.xml`, 'xml',
					'https://www.senate.gov/legislative/LIS/roll_call_votes/vote1191/vote_119_1_00318.htm')
			],
			'amendment-2': [
				src('House Roll Call Vote #200', `${usBase}/vote-house-200.xml`, 'xml',
					'https://clerk.house.gov/Votes/2025200')
			],
			final: [
				src('S.1582 — Enrolled Bill', `${usBase}/03-enr.xml`, 'xml',
					`${congressGov}/bill/119th-congress/senate-bill/1582/text/enr`)
			]
		};
		return docs[versionSlug] || [];
	}

	// ── Ley 21.120 — Identidad de Género (Boletín 8924-07) ──
	if (boletinSlug === 'ley-21120-boletin') {
		const docs: Record<string, SourceRef[]> = {
			bill: [
				src('Moción Original', `${LEY_21120_DOCS}/01-mocion.txt`, 'text',
					senadoDocUrl(9331, 'mensaje_mocion'))
			],
			'amendment-1': [
				src('Primer Informe DDHH Senado', `${LEY_21120_DOCS}/02-primer-informe-ddhh.txt`, 'text',
					senadoDocUrl(16215, 'info')),
				src('Oficio Ley a Cámara', `${LEY_21120_DOCS}/04-oficio-ley-camara.txt`, 'text',
					senadoDocUrl(22438, 'ofic'))
			],
			'amendment-2': [
				src('Informe DDHH Cámara (2do Trámite)', `${LEY_21120_DOCS}/05-informe-camara.txt`, 'text',
					senadoDocUrl(20196, 'info'))
			],
			'amendment-3': [
				src('Informe Comisión Mixta', `${LEY_21120_DOCS}/08-informe-comision-mixta.txt`, 'text',
					senadoDocUrl(20587, 'info'))
			],
			final: [
				src('Ley 21.120 — LeyChile', `${LEY_21120_DOCS}/leychile-21120.json`, 'json',
					leyChileUrl(1126480))
			]
		};
		return docs[versionSlug] || [];
	}

	// ── ES Tramitación — bills in parliamentary process ──
	if (boletinSlug?.startsWith('es-tram-')) {
		// Source documents are the BOCG text files + Congreso JSON
		// Map boletin slug to data dir: es-tram-economia-social → 121-000036
		const tramDirs: Record<string, string> = {
			'es-tram-economia-social': '121-000036',
			'es-tram-desperdicio-alimentario': '121-000004',
			'es-tram-menores-digitales': '121-000052',
			'es-tram-jornada-laboral': '121-000058'
		};
		const dataDir = tramDirs[boletinSlug] || boletinSlug.replace('es-tram-', '');
		const esBase = `pipeline/data/es/${dataDir}/sources`;
		return [
			src('Congreso Open Data', `${esBase}/congreso-proyectos.json`, 'json',
				'https://www.congreso.es/es/opendata/iniciativas'),
			src('Discovery Metadata', `${esBase}/../discovery.json`, 'json')
		];
	}

	// ── ES — BOE consolidated laws ──
	if (boletinSlug?.startsWith('es-')) {
		const boeIds: Record<string, string> = {
			'es-lo3-2018-proteccion-datos': 'BOE-A-2018-16673',
			'es-ley39-2015-procedimiento-administrativo': 'BOE-A-2015-10565',
			'es-lssi-2002': 'BOE-A-2002-13758',
			'es-telecom-2022': 'BOE-A-2022-10757'
		};
		const boeId = boeIds[boletinSlug];
		if (boeId) {
			const esBase = `pipeline/data/es/${boeId}/sources`;
			const boeUrl = `https://www.boe.es/buscar/act.php?id=${boeId}`;
			// All versions link to the BOE consolidated text + XML sources
			return [
				src(`BOE Texto Consolidado`, `${esBase}/boe-${boeId}-texto.xml`, 'xml', boeUrl),
				src(`BOE Metadatos`, `${esBase}/boe-${boeId}-metadata.xml`, 'xml', boeUrl)
			];
		}
	}

	return [];
}

export async function loadBoletin(slug: string): Promise<Boletin> {
	const dirName = BOLETIN_DIRS[slug];
	if (!dirName) {
		throw new Error(`Unknown boletin: ${slug}`);
	}

	const dirPath = join(process.cwd(), dirName);
	const files = await readdir(dirPath);
	const xmlFiles = files.filter((f) => f.endsWith('.xml')).sort();

	const documents: AknDocument[] = [];
	for (const file of xmlFiles) {
		const xml = await readFile(join(dirPath, file), 'utf-8');
		documents.push(parseAknDocument(xml, file));
	}

	// Get title from original act, or first document if no act
	const original = documents.find((d) => d.type === 'act' && fileToSlug(d.fileName) === 'original');
	const title = original?.prefaceTitle || documents[0]?.prefaceTitle || slug;

	const boletin: Boletin = {
		slug,
		title,
		documents,
		timeline: buildTimeline(documents, slug)
	};

	// ES — enrich timeline with per-amendment source links from config.json
	if (slug.startsWith('es-')) {
		const configPath = join(dirPath, '..', 'config.json');
		try {
			const configRaw = await readFile(configPath, 'utf-8');
			const esConfig = JSON.parse(configRaw);
			if (esConfig.timeline) {
				const isTramitacion = slug.startsWith('es-tram-');
				const boe = 'https://www.boe.es/buscar';
				for (const entry of boletin.timeline) {
					const configEntry = esConfig.timeline.find(
						(t: { slug: string }) => t.slug === entry.slug
					);
					if (!configEntry) continue;
					if (isTramitacion && configEntry.sourceUrl) {
						// Tramitación: source URLs point to BOCG PDFs
						entry.sourceUrl = configEntry.sourceUrl;
						entry.sourceLabel = 'BOCG (Congreso)';
					} else if (entry.type === 'amendment' && configEntry.modifyingLaw) {
						entry.sourceUrl = `${boe}/doc.php?id=${configEntry.modifyingLaw}`;
						entry.sourceLabel = 'BOE (ley modificadora)';
					} else if (entry.type === 'act') {
						const boeId = esConfig.boeId;
						const dateParam = entry.date.replace(/-/g, '');
						entry.sourceUrl = `${boe}/act.php?id=${boeId}&p=${dateParam}`;
						entry.sourceLabel = 'BOE (texto consolidado)';
					}
				}
			}
		} catch {
			// No config.json — use default links
		}
	}

	// Load supplementary metadata if available (EU regulations)
	const metadataPath = join(dirPath, '00-metadata.json');
	try {
		const metadataRaw = await readFile(metadataPath, 'utf-8');
		const metadata = JSON.parse(metadataRaw);

		if (metadata.procedureEvents) {
			boletin.procedureEvents = (metadata.procedureEvents as ProcedureEvent[])
				.sort((a, b) => a.date.localeCompare(b.date));
		}

		if (metadata.rapporteur) {
			// Set rapporteur on any document that has a vote
			for (const doc of boletin.documents) {
				if (doc.changeSet?.vote) {
					doc.changeSet.vote.rapporteur = metadata.rapporteur;
				}
			}
		}
	} catch {
		// No metadata file — that's fine (Chile boletins, etc.)
	}

	return boletin;
}

export async function listBoletines(slugFilter?: string[]): Promise<{ slug: string; title: string; documentCount: number }[]> {
	const entries = slugFilter
		? Object.entries(BOLETIN_DIRS).filter(([slug]) => slugFilter.includes(slug))
		: Object.entries(BOLETIN_DIRS);

	const result: { slug: string; title: string; documentCount: number }[] = [];

	for (const [slug, dirName] of entries) {
		const dirPath = join(process.cwd(), dirName);
		const files = await readdir(dirPath);
		const xmlFiles = files.filter((f) => f.endsWith('.xml'));

		// Read original to get title
		const originalFile = xmlFiles.find((f) => f.startsWith('01-'));
		let title = slug;
		if (originalFile) {
			const xml = await readFile(join(dirPath, originalFile), 'utf-8');
			const doc = parseAknDocument(xml, originalFile);
			title = doc.prefaceTitle || slug;
		}

		result.push({ slug, title, documentCount: xmlFiles.length });
	}

	return result;
}

export function getVersionIndex(boletin: Boletin, versionSlug: string): number {
	const idx = boletin.timeline.findIndex((t) => t.slug === versionSlug);
	if (idx === -1) throw new Error(`Unknown version: ${versionSlug}`);
	return idx;
}
